export const HOME_ROUTE = 'HOME_ROUTE';
export const HOUSES_ROUTE = 'HOUSES_ROUTE';
export const SUCCESS_HOUSES = 'SUCCESS_HOUSES';
export const FAILURE_HOUSES = 'FAILURE_HOUSES';
export const LOADING_HOUSES = 'LOADING_HOUSES';
// export const SUCCESS_REPOS = 'SUCCESS_REPOS';
// export const FAILURE_REPOS = 'FAILURE_REPOS';
